# Generated by Django 3.2.4 on 2021-06-09 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Compte', 'verbose_name_plural': 'Comptes'},
        ),
    ]
